version: "3"
services:
  vulnapp:
    build: ./vulnapp
    ports:
      - "5000:5000"
    env_file:
      - sample-env.list
  xssbot:
    build: ./xssbot
    ports:
      - "5555:5555"
    env_file:
      - sample-env.list
